### ISSUE TITLE
Display Visual tags pertaining to the category on the gallery cards

### ISSUE THREAD

**Issue by NihanthCW** [NCAR/cisl-visualization-gallery#17]
It will be immensely helpful to denote the type of visualization on the gallery card. Example screenshot- doesn't have to be the same color.
![Screenshot 2024-09-24 at 1 51 35 PM](https://github.com/user-attachments/assets/bd8fbb36-caab-4cb2-9de3-30613c7fa198)

**Comment by tammyzhang-1** [comment]
Just pushed some tags - take a look and let me know if you'd like to adjust the styling!
